name: Rust tests

on:
  push:
    branches: [stable]
  pull_request:
  workflow_call:

permissions:
  contents: read

concurrency:
  group: rust-tests-${{ github.event_name }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  rust:
    uses: blacklanternsecurity/CLA/.github/workflows/rust-tests.yml@883bfbc89464cadbeb10307b2b82891ba7853f56 # 2026-10-03
    with:
      cargo-args: --all-features --locked
